### ISSUE TITLE
Will not build

### ISSUE THREAD

**Issue by Hphipps** [ARMmbed/mbed-aws-client#2]
Failed to add library mbed-aws-client with the following errors: - mbed-aws-client/tinycbor: No valid .lib file found

**Comment by ashok-rao** [comment]
Hi @Hphipps .. Can you tell us a bit more about your build env?

**Comment by LDong-Arm** [comment]
Hi @Hphipps, could you try to remove the slash `\` from `mbed-aws-client/tinycbor.lib`? This should resolve the fetching issue.

Sorry we will have this fixed very soon.
